package flag

import (
	"fmt"
	"strings"
)

// BlobLen is FLAG_BLOB's length: the flag and its NUL.
const BlobLen = Len + 1

// xorshift32 is the keystream both sides use. A zero state would stay zero, so it is
// replaced by a fixed odd constant (the C side does the same).
func xorshift32(s uint32) uint32 {
	s ^= s << 13
	s ^= s >> 17
	s ^= s << 5
	return s
}

func seed(key, mix uint32) uint32 {
	if s := key ^ mix; s != 0 {
		return s
	}
	return 0x9e3779b9
}

// Encode XORs the flag (and its NUL) with the keystream for key, so that only a program
// holding key at runtime can decode it (ADR 0005).
func Encode(flag string, key, mix uint32) [BlobLen]byte {
	var out [BlobLen]byte
	s := seed(key, mix)
	src := []byte(flag + "\x00")
	for i := range out {
		s = xorshift32(s)
		out[i] = src[i] ^ byte(s)
	}
	return out
}

// Decode is the Go twin of the generated flag_decode, for tests.
func Decode(blob [BlobLen]byte, key, mix uint32) string {
	s := seed(key, mix)
	var out [BlobLen]byte
	for i := range out {
		s = xorshift32(s)
		out[i] = blob[i] ^ byte(s)
	}
	return string(out[:Len])
}

// Header renders flag_blob.h for a challenge: FLAG_BLOB, FLAG_SEED_MIX and flag_decode.
// The flag itself never appears in it.
func Header(slug, secret string, key uint32) string {
	mix := SeedMix(secret, slug)
	blob := Encode(Derive(secret, slug), key, mix)
	var b strings.Builder
	fmt.Fprintf(&b, "/* flag_blob.h for %s, generated by labd/cmd/flagblob (ADR 0005).\n", slug)
	b.WriteString(" * Build input only: never commit it, never copy it into an image. */\n")
	b.WriteString("#ifndef FLAG_BLOB_H\n#define FLAG_BLOB_H\n\n")
	fmt.Fprintf(&b, "static const unsigned char FLAG_BLOB[%d] = {", BlobLen)
	for i, c := range blob {
		if i%10 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "0x%02x,", c)
	}
	b.WriteString("\n};\n")
	fmt.Fprintf(&b, "static const unsigned FLAG_SEED_MIX = 0x%08xu;\n\n", mix)
	fmt.Fprintf(&b, `/* Decodes FLAG_BLOB with the runtime key. The right key gives the flag; any other key
 * gives %d bytes of garbage. out must hold %d bytes. */
static inline void flag_decode(unsigned key, char out[%d])
{
	unsigned s = key ^ FLAG_SEED_MIX;
	if (s == 0)
		s = 0x9e3779b9u;
	for (int i = 0; i < %d; i++) {
		s ^= s << 13;
		s ^= s >> 17;
		s ^= s << 5;
		out[i] = (char)(FLAG_BLOB[i] ^ (unsigned char)s);
	}
	out[%d] = 0;
}

#endif
`, Len, BlobLen, BlobLen, BlobLen, Len)
	return b.String()
}
