# Generated by Django 5.2.17 on 2026-10-01 13:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.TextField()),
                ('user_id', models.BigIntegerField(null=True)),
                ('session_id', models.UUIDField(null=True)),
                ('challenge_slug', models.TextField(null=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('challenge_slug', models.TextField()),
                ('image', models.TextField(default='')),
                ('state', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('end_reason', models.TextField(default='')),
                ('container_id', models.TextField(default='')),
                ('extended', models.BooleanField(default=False)),
                ('peak_rss_mb', models.FloatField(null=True)),
                ('commands', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
    ]
