# Generated by Django 5.2.17 on 2026-10-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('ts', models.DateTimeField(primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(null=True)),
                ('metric', models.TextField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'samples',
                'managed': False,
            },
        ),
    ]
