#!/usr/bin/env bash
# p1.sh — Phase 3, task 3.10: P1, one session driven like a person for --duration.
#
#   labd/perf/p1.sh [--duration 600] [--rate 20] [--out DIR]
#
# Starts a private labd (lib.sh), then the replay command: POST /internal/sessions, the
# WebSocket, gdb on the perf binary, and images/perf/session.gdb replayed at --rate commands a
# minute (looped) for --duration seconds. Meanwhile, every 5 s, samples from the host: the
# lab cgroup's memory.current (the whole sandbox), the Sentry's RSS, and cpu.stat usage_usec.
# Output: DIR/p1-<date>-<host>.json and .md (default docs/metrics).
set -euo pipefail
# shellcheck source=lib.sh disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

DURATION=600 RATE=20 OUT="$PERF_ROOT/docs/metrics"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --duration) DURATION="$2"; shift 2 ;;
    --rate) RATE="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    *) echo "usage: p1.sh [--duration S] [--rate N] [--out DIR]" >&2; exit 2 ;;
  esac
done

perf_init 5
trap perf_cleanup EXIT
say "building the replay command"
(cd "$PERF_ROOT/labd" && go build -o bin/replay ./internal/term/client/cmd/replay)
start_labd

SUMMARY="$WORK/replay.json" SID_FILE="$WORK/session" SAMPLES="$WORK/samples.tsv"
say "replaying session.gdb at $RATE commands/min for ${DURATION}s"
"$PERF_ROOT/labd/bin/replay" -api "$API" -ws "ws://127.0.0.1:18082" -rate "$RATE" \
  -duration "${DURATION}s" -script "$PERF_ROOT/images/perf/session.gdb" \
  -out "$SUMMARY" -session-file "$SID_FILE" &
replay_pid=$!

have_sid() { [[ -s "$SID_FILE" ]]; }
wait_until 60 "the replay's session id" have_sid
sid="$(tr -d '\n' < "$SID_FILE")"
cg="/sys/fs/cgroup/labs/lab-$sid"
is_running() { [[ "$(api GET /internal/sessions | jq -r --arg id "$sid" '.sessions[] | select(.session_id == $id) | .state')" == running ]]; }
wait_until 60 "session $sid running" is_running
say "sampling $cg every 5 s"
cpu0="$(awk '/^usage_usec/{print $2}' "$cg/cpu.stat")"; t0=$(date +%s%N)
: > "$SAMPLES"
while kill -0 "$replay_pid" 2>/dev/null; do
  mem="$(awk '{printf "%.1f", $1/1048576}' "$cg/memory.current" 2>/dev/null || echo)"
  pid="$(pgrep -f -- "runsc-sandbox.*lab-$sid" | head -n1 || true)"
  rss="$( [[ -n "$pid" ]] && awk '/^VmRSS:/{printf "%.1f", $2/1024}' "/proc/$pid/status" 2>/dev/null || echo 0)"
  cpu="$(awk '/^usage_usec/{print $2}' "$cg/cpu.stat" 2>/dev/null || echo)"
  [[ -n "$mem" && -n "$cpu" ]] && printf '%s\t%s\t%s\t%s\n' "$(date +%s%N)" "$mem" "$rss" "$cpu" >> "$SAMPLES"
  sleep 5
done
wait "$replay_pid" || die "replay failed (labd log: $LABD_LOG)"
[[ -s "$SAMPLES" ]] || die "no samples taken"

# CPU: host cgroup time over wall time (gVisor's in-sandbox clock over-reports; Phase 1).
last="$(tail -n1 "$SAMPLES")"
cpu_pct="$(awk -v c0="$cpu0" -v t0="$t0" -v l="$last" 'BEGIN{split(l,f,"\t"); printf "%.2f", (f[4]-c0)/((f[1]-t0)/1000)*100}')"
col() { cut -f"$1" "$SAMPLES"; }
mem50="$(col 2 | pct 50)" mem95="$(col 2 | pct 95)" memx="$(col 2 | sort -n | tail -n1)"
rss50="$(col 3 | pct 50)" rss95="$(col 3 | pct 95)" rssx="$(col 3 | sort -n | tail -n1)"
n_samples="$(wc -l < "$SAMPLES" | tr -d ' ')"

host="$(host_label)" stamp="$(date -u +%Y-%m-%d)"
runtime="$(sed -n 's/^runtime: *//p' "$LABD_CFG")"
mkdir -p "$OUT"
json="$OUT/p1-$stamp-$host.json" md="$OUT/p1-$stamp-$host.md"
jq --arg host "$host" --arg arch "$(uname -m)" --arg kernel "$(uname -r)" --arg date "$(date -u +%FT%TZ)" \
  --arg runtime "$runtime" --arg runsc "$(runsc --version 2>/dev/null | sed -n 1p)" \
  --argjson rate "$RATE" --argjson samples "$n_samples" \
  --argjson m50 "$mem50" --argjson m95 "$mem95" --argjson mx "$memx" \
  --argjson r50 "$rss50" --argjson r95 "$rss95" --argjson rx "$rssx" --argjson cpu "$cpu_pct" \
  '{host:$host, arch:$arch, kernel:$kernel, date:$date, runtime:$runtime, runsc:$runsc,
    profile:"stepper", rate_per_min:$rate, duration_s:.duration_s,
    start_to_prompt_ms:.start_to_prompt_ms, echo_latency_ms:.echo_latency_ms,
    cgroup_mem_mb:{p50:$m50, p95:$m95, max:$mx}, sentry_rss_mb:{p50:$r50, p95:$r95, max:$rx},
    cpu_pct_avg:$cpu, ws_bytes_in:.ws_bytes_in, ws_bytes_out:.ws_bytes_out,
    ws_bps_in:(.ws_bytes_in / .duration_s), ws_bps_out:(.ws_bytes_out / .duration_s),
    commands:.commands, command_errors:.errors, samples:$samples, units:"memory in MiB"}' "$SUMMARY" > "$json"
{
  echo "# P1 — single session, $host, $stamp"
  echo
  echo "Host \`$host\` ($(uname -m), kernel $(uname -r)), $(runsc --version 2>/dev/null | sed -n 1p), runtime \`$runtime\`."
  echo "Generated by \`labd/perf/p1.sh --duration $DURATION --rate $RATE\`: \`images/perf/session.gdb\` replayed over the WebSocket gateway; host samples every 5 s. Raw data in \`$(basename "$json")\`."
  echo
  echo "| Metric | Value |"
  echo "| --- | --- |"
  jq -r '"| Start to gdb prompt (API request to `(gdb) ` over the socket) | \(.start_to_prompt_ms) ms |",
         "| Echo latency p50 / p95 / max (command sent to first byte back) | \(.echo_latency_ms.p50) / \(.echo_latency_ms.p95) / \(.echo_latency_ms.max) ms |",
         "| Commands (errors) over \(.duration_s) s | \(.commands) (\(.command_errors)) |",
         "| Lab cgroup memory p50 / p95 / max | \(.cgroup_mem_mb.p50) / \(.cgroup_mem_mb.p95) / \(.cgroup_mem_mb.max) MiB |",
         "| Sentry RSS p50 / p95 / max (includes shared pages) | \(.sentry_rss_mb.p50) / \(.sentry_rss_mb.p95) / \(.sentry_rss_mb.max) MiB |",
         "| CPU, host cgroup, average | \(.cpu_pct_avg) % of a core |",
         "| WebSocket bytes in / out (keystrokes / terminal output) | \(.ws_bytes_in) / \(.ws_bytes_out) |",
         "| WebSocket bytes/s in / out | \(.ws_bps_in | floor) / \(.ws_bps_out | floor) |"' "$json"
  echo
  echo "Spec pass criterion (P1): start latency p95 < 2 s. One session gives one start: $(jq -r 'if .start_to_prompt_ms < 2000 then "met" else "NOT met" end' "$json") ($(jq .start_to_prompt_ms "$json") ms)."
} > "$md"
say "wrote ${json#"$PERF_ROOT"/} and ${md#"$PERF_ROOT"/}"
jq -c '{start_to_prompt_ms, echo_latency_ms, cgroup_mem_mb, cpu_pct_avg, commands, command_errors}' "$json" >&2
