# Generated by Django 5.2.17 on 2026-10-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rollup1h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_ts', models.DateTimeField()),
                ('metric', models.CharField(max_length=100)),
                ('dims', models.JSONField(default=dict)),
                ('dims_key', models.CharField(default='{}', max_length=300)),
                ('count', models.BigIntegerField()),
                ('sum', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('p50', models.FloatField()),
                ('p95', models.FloatField()),
            ],
            options={
                'db_table': 'rollups_1h',
                'indexes': [models.Index(fields=['metric', 'bucket_ts'], name='rollups_1h_metric_ts')],
                'constraints': [models.UniqueConstraint(fields=('bucket_ts', 'metric', 'dims_key'), name='rollups_1h_key')],
            },
        ),
        migrations.CreateModel(
            name='Rollup1m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_ts', models.DateTimeField()),
                ('metric', models.CharField(max_length=100)),
                ('dims', models.JSONField(default=dict)),
                ('dims_key', models.CharField(default='{}', max_length=300)),
                ('count', models.BigIntegerField()),
                ('sum', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('p50', models.FloatField()),
                ('p95', models.FloatField()),
            ],
            options={
                'db_table': 'rollups_1m',
                'indexes': [models.Index(fields=['metric', 'bucket_ts'], name='rollups_1m_metric_ts')],
                'constraints': [models.UniqueConstraint(fields=('bucket_ts', 'metric', 'dims_key'), name='rollups_1m_key')],
            },
        ),
    ]
