# Generated by Django 5.2.17 on 2026-10-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'tiers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body_md', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.tier')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['tier__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('image_digest', models.CharField(blank=True, max_length=300)),
                ('limits', models.JSONField(default=dict)),
                ('hints', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('estimated_minutes', models.PositiveSmallIntegerField()),
                ('boss', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('solution_md', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge', to='curriculum.lesson')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='curriculum.tier')),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['tier__order', 'order'],
            },
        ),
    ]
