package perf

import (
	"errors"
	"fmt"
	"strings"
)

// Markers around the part of docs/metrics/capacity.md that labd-perf report writes. Text
// outside them (the introduction, Phase 1 rows, dev VM observations, "Failures and
// decisions") is kept as it is.
const (
	BlockBegin = "<!-- labd-perf report: begin (generated; edit outside these markers) -->"
	BlockEnd   = "<!-- labd-perf report: end -->"
)

// ReplaceBlock swaps the generated block in md for block.
func ReplaceBlock(md, block string) (string, error) {
	i := strings.Index(md, BlockBegin)
	j := strings.Index(md, BlockEnd)
	if i < 0 || j < i {
		return "", errors.New("capacity.md has no labd-perf report markers")
	}
	return md[:i] + BlockBegin + "\n" + block + md[j:], nil
}

// RenderCapacity is the generated block: every number with the run file it came from.
func RenderCapacity(rep Report, runs map[string]LoadedRun, missing []string) string {
	var b strings.Builder
	src := func(field string) string {
		if f := rep.Meta.Sources[field]; f != "" {
			return "`" + f + "`"
		}
		return "not measured"
	}
	file := func(key string) string {
		if lr, ok := runs[key]; ok {
			return "`" + lr.File + "`"
		}
		return "not run"
	}
	sum := func(key string) (RunSummary, bool) {
		lr, ok := runs[key]
		return lr.Run.Summary, ok
	}
	n := func(key string) int { return runs[key].Run.Meta.N }
	host := rep.Meta.Host
	row := func(cells ...string) { b.WriteString("| " + strings.Join(cells, " | ") + " |\n") }

	fmt.Fprintf(&b, "Generated by `labd-perf report` from the newest run of each scenario on `%s` (%s), last run %s. Memory in MiB unless marked MB.\n\n", host, rep.Meta.Arch, rep.Meta.Date)
	if len(rep.Meta.Partial) > 0 {
		b.WriteString("**Partial:** " + strings.Join(rep.Meta.Partial, "; ") + ". The full run is repeated on the VPS in Phase 8, task 8.8.\n\n")
	}

	b.WriteString("### Per lab (Phase 4)\n\n| Resource | Value | Host | Source |\n| --- | --- | --- | --- |\n")
	if s, ok := sum("P2"); ok {
		row("Memory: cgroup `memory.current` at N", fmt.Sprintf("p50 %.1f, p95 %.1f, max %.1f (%d readers at gdb, every lab every 5 s over the hold)",
			s.LabMemMB.P50, s.LabMemMB.P95, s.LabMemMB.Max, n("P2")), host, file("P2"))
		row("Memory: whole cost per lab on the host", fmt.Sprintf("%.1f MB: (peak used − idle) / labs; includes each lab's containerd shim, which is outside its cgroup", s.HostPerLabMB), host, file("P2"))
		row("Memory: Sentry RSS", fmt.Sprintf("p50 %.1f, p95 %.1f (RSS counts shared pages)", s.SentryRSSMB.P50, s.SentryRSSMB.P95), host, file("P2"))
		row("CPU: idle (reader: 2 commands/min, 30 % idle)", fmt.Sprintf("%.2f %% of a core, average", s.LabCPUPctAvg), host, file("P2"))
	}
	if s, ok := sum("P8"); ok {
		row("CPU: during `step` loops (stepper, 20 commands/min)", fmt.Sprintf("%.2f %% of a core, average over %d labs", s.LabCPUPctAvg, n("P8")), host, file("P8"))
		row("Bandwidth: WS bytes/s per active terminal", fmt.Sprintf("%.0f B/s out, %.1f B/s in (stepper; payload, no TLS framing: about +5 %% behind Caddy)", s.WSBpsOut, s.WSBpsIn), host, file("P8"))
	}
	if rep.PerLab.DiskMB > 0 || rep.Meta.Sources["per_lab.disk_mb"] != "" {
		row("Disk: writable snapshot per session", fmt.Sprintf("%.2f MB (snapshot store growth / labs at N)", rep.PerLab.DiskMB), host, src("per_lab.disk_mb"))
	}
	if s, ok := sum("P2"); ok {
		row("Start latency: request to gdb prompt under the ramp", fmt.Sprintf("p50 %.0f ms, p95 %.0f ms (%d starts at %.0f/s)", s.StartToPromptMS.P50, s.StartToPromptMS.P95, s.StartToPromptMS.N, runs["P2"].Run.Meta.Ramp), host, file("P2"))
	}
	if s, ok := sum("P3"); ok {
		row("Echo latency p95 at N (mixed load)", fmt.Sprintf("p95 %.1f ms, p50 %.1f ms over %d commands", s.EchoMS.P95, s.EchoMS.P50, s.EchoMS.N), host, file("P3"))
	}

	b.WriteString("\n### Host at N labs (Phase 4)\n\n| Resource | Value | Host | Source |\n| --- | --- | --- | --- |\n")
	if s, ok := sum("P2"); ok {
		row(fmt.Sprintf("Memory used at %d readers", n("P2")), fmt.Sprintf("%.0f MB peak, %.0f MB with no lab", s.HostMemUsedMB.Max, s.HostBaselineMB), host, file("P2"))
	}
	if s, ok := sum("P3"); ok {
		row(fmt.Sprintf("CPU at %d mixed (60/30/10)", n("P3")), fmt.Sprintf("%.1f %% of all host CPUs p50, %.1f %% p95 (abusers burn their 0.5-core quota)", s.HostCPUPct.P50, s.HostCPUPct.P95), host, file("P3"))
		row("Memory and CPU pressure at N (PSI some avg10, max)", fmt.Sprintf("memory %.2f, cpu %.2f, io %.2f", s.PSIMax.Memory, s.PSIMax.CPU, s.PSIMax.IO), host, file("P3"))
	}
	if s, ok := sum("P2"); ok {
		row("labd at N", fmt.Sprintf("%.0f MiB RSS, %.0f goroutines (idle: %.0f MiB, %.0f)", s.LabdRSSMB.Peak, s.LabdGoroutines.Peak, s.LabdRSSMB.Idle, s.LabdGoroutines.Idle), host, file("P2"))
		row("containerd at N", fmt.Sprintf("%.0f MiB RSS (idle %.0f)", s.ContainerdRSSMB.Peak, s.ContainerdRSSMB.Idle), host, file("P2"))
	}
	if img, ok := rep.Extra["images_mib"].(map[string]any); ok {
		row("Disk: images (200 challenges)", fmt.Sprintf("about %.0f MiB: labbase %.1f + 200 × %.2f (the perf program layer; real challenge layers are measured in Phase 5)",
			img["challenges_200_estimate_basis"], img["labbase"], img["program_layer"]), host, fmt.Sprint("`", img["file"], "`"))
	}
	if p9, ok := rep.Extra["p9"].(map[string]any); ok {
		row("Disk: data per session-minute", fmt.Sprintf("%v KB of `events` (%v rows); `samples` is written from Phase 7 and re-measured then", p9["events_kb_per_session_minute"], p9["events_rows_per_session_minute"]), host, file("P9"))
		row("Disk growth per hour at N, churning", fmt.Sprintf("snapshots %v MB, journal %v MB, events %v MB", p9["snapshots_mb_per_hour"], p9["journal_mb_per_hour"], p9["events_mb_per_hour"]), host, file("P9"))
	}
	if s, ok := sum("P8"); ok {
		row(fmt.Sprintf("Bandwidth aggregate at %d steppers", n("P8")), fmt.Sprintf("%.0f B/s out (%.3f Mbps)", s.WSBpsOutAggregate, s.WSBpsOutAggregate*8/1e6), host, file("P8"))
	}

	b.WriteString("\n### gVisor overhead (runsc against runc)\n\n| Metric | runc | runsc | Host | Source |\n| --- | --- | --- | --- | --- |\n")
	if s, ok := sum("P1"); ok {
		r, _ := sum("P1-runc")
		row("`step`/`next` time to gdb's prompt, p50", fmt.Sprintf("%.2f ms", r.StepCmdMS.P50), fmt.Sprintf("%.2f ms (%.1f×)", s.StepCmdMS.P50, ratio(s.StepCmdMS.P50, r.StepCmdMS.P50)), host, file("P1")+", "+file("P1-runc"))
		row("`step`/`next` time to gdb's prompt, p95", fmt.Sprintf("%.2f ms", r.StepCmdMS.P95), fmt.Sprintf("%.2f ms", s.StepCmdMS.P95), host, file("P1")+", "+file("P1-runc"))
	}
	for _, k := range []string{"P2", "P3"} {
		s, ok := sum(k)
		r, okr := sum(k + "-runc")
		if ok && okr {
			row(fmt.Sprintf("Memory per lab at N (%s), whole host cost", k), fmt.Sprintf("%.1f MB", r.HostPerLabMB), fmt.Sprintf("%.1f MB (+%.1f)", s.HostPerLabMB, s.HostPerLabMB-r.HostPerLabMB), host, file(k)+", "+file(k+"-runc"))
		}
	}
	for _, k := range []string{"P1", "P2"} {
		s, ok := sum(k)
		kv, okk := sum(k + "-kvm")
		if ok && okk {
			row(fmt.Sprintf("%s under runsc KVM platform: start p95, echo p95, step p50", k), "systrap: "+fmt.Sprintf("%.0f ms, %.1f ms, %.2f ms", s.StartToPromptMS.P95, s.EchoMS.P95, s.StepCmdMS.P50),
				fmt.Sprintf("kvm: %.0f ms, %.1f ms, %.2f ms", kv.StartToPromptMS.P95, kv.EchoMS.P95, kv.StepCmdMS.P50), host, file(k+"-kvm"))
		}
	}

	b.WriteString("\n### Leaks and derived capacity\n\n| Value | Result | Source |\n| --- | --- | --- |\n")
	row("Leaks after every run (containers, labd goroutines, FIFOs)", fmt.Sprintf("%d, %d, %d (worst run)", rep.Leaks.Containers, rep.Leaks.Goroutines, rep.Leaks.FIFOs), "every run file")
	if d, ok := rep.Extra["derived_inputs"].(map[string]any); ok {
		row("`max_sessions` at 25 % memory headroom on 32 GB", fmt.Sprintf("**%d** = floor((32768 × 0.75 − %.0f) / %.1f). %v", rep.Derived.MaxSessionsAt25pctHeadroom, d["baseline_mb"], d["per_lab_mb"], d["note"]), src("derived.max_sessions_at_25pct_headroom"))
	}

	b.WriteString("\n### Scenario results against the spec's pass criteria\n\n| Scenario | Criterion | Measured | Result | Source |\n| --- | --- | --- | --- | --- |\n")
	for _, k := range sortedKeys(runs) {
		for _, c := range runs[k].Run.Criteria {
			v := "pass"
			if !c.Pass {
				v = "**miss**"
			}
			row(k, c.Criterion, strings.ReplaceAll(c.Measured, "|", "/"), v, file(k))
		}
	}
	if len(missing) > 0 {
		b.WriteString("\nNot measured yet: " + strings.Join(missing, "; ") + ".\n")
	}
	b.WriteString("\n")
	return b.String()
}

func ratio(a, b float64) float64 {
	if b == 0 {
		return 0
	}
	return a / b
}
